### ISSUE TITLE
Fix bug: A laboratory report

### ISSUE THREAD

**Issue by Ramadhani202208** [udsm-dhis2-lab/iCareConnect#75]
**Describe the bug**
Fix bug: A laboratory report to show the data for TAT report

**To Reproduce**
1. Please login in the system using the link "icare-serenederm.dhis2.udsm.ac.tz" username: admin, Password: Admin123"
2. Go to 'Laboratory module'
3. Click on 'report'
4. Select TAT report, 
5. Then, select date range
6. See error

**Expected behavior**
A user expect to view the report but there is error.

**Screenshots**
![Lab report](https://user-images.githubusercontent.com/111587628/203779685-2b1af555-d0b3-48a2-aa5a-417c61fb5adc.png)

**Additional context**

**Comment by klaus-gudy** [comment]
I looked up some of the relevant TAT medical reports but couldn't find any. It will be considerably easier if we can receive a sample of the physical copy of the TAT report. We're experiencing difficulties determining how they look.

**Comment by Ramadhani202208** [comment]
Hello, you will be given a sample. Remind you that TAT report shows  the
summary of test performed at laboratory at a given time that means (TURN
AROUND TIME) report.
Thanks and regards
